NAG_Img_finder/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nif.urls'))

]

nif/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:product_id>/', views.detail, name='detail'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),

 ]

nif/models.py
from django.db import models

# Create your models here.

class Product(models.Model):

    title = models.CharField(max_length=255)
    sku = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.title



class Image(models.Model):

    url = models.URLField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.url

nif/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField()

nif/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from django.db.models import Q
from django.template import Context, loader
from django.http import HttpResponse

from .models import Product

# Create your views here.

def index(request):
    return render(request, 'index.html')

def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'detail.html', {'product': product})



class SearchResultsView(ListView):
    model = Product
    template_name = 'search_result.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(
            Q(title__icontains=query) | Q(sku__icontains=query)
        )
        return object_list

templates/detail.html
<head>
  <link
    rel="stylesheet"
    href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
  />
  <link
    rel="stylesheet"
    href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"
  />
</head>

<div class="sresult">
  <h3>{{ product.title }}</h3>
  <p>Для увеличения нажать на картинку</p>
  <div>
    {% for img in product.image_set.all %}
    <div>
      <a href="{{ img }}"><img src="{{ img }}"/></a>
    </div>

    {% endfor %}
  </div>
</div>
<style>
  img {
    height: 250px;
    float: left;
  }

  .sresult {
    width: 80%;
    margin: auto;
  }
</style>

templates/index.html
<head>
  <link
    rel="stylesheet"
    href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
  />
  <link
    rel="stylesheet"
    href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"
  />
  <link rel="stylesheet" href="/static/style.css" />
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script defer src="/static/script.js"></script>
</head>

<body>
  <div class="searchform">
    <h4>Поиск оборудования в БД НАГ</h4>
    <form action="{% url 'search_results' %}" method="get">
      <input
        id="search"
        class="form-control"
        required
        name="q"
        type="text"
        placeholder="Ввести код, или наименование с учетом регистра"
      />
    </form>
  </div>
</body>

templates/search_result.html
<head>
  <link
    rel="stylesheet"
    href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
  />
  <link
    rel="stylesheet"
    href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"
  />
  <link rel="stylesheet" href="/static/style.css" />
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script defer src="/static/script.js"></script>
</head>

<div class="searchline">
    <form action="{% url 'search_results' %}" method="get">
      <input
        id="search"
        class="form-control"
        required
        name="q"
        type="text"
        placeholder="Ввести код, или наименование с учетом регистра"
      />
    </form>
</div>

<div class="searchres">
  <h3 class="table">Результаты поиска</h3>
  {% if object_list %}
  <table class="table">
    <thead>
      <tr>
        <th>
          Код
        </th>
        <th>
          Наименование
        </th>
      </tr>
    </thead>
    <tbody>
      {% for item in object_list %}
      <tr>
        <td>
          <a href="/{{ item.id }}/">{{ item.sku }}</a>
        </td>
        <td>
          <a href="/{{ item.id }}/">{{ item.title }}</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p>Ничего не найдено</p>
  {% endif %}
</div>
<style>
  .searchres {
    width: 80%;
    margin: auto;
  }
</style>